-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS "messages";

CREATE TABLE "messages" (
    "id" BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "author" VARCHAR NOT NULL,
    "text" VARCHAR NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL
) ;
CREATE INDEX messages_author_created_at ON "messages" ("author", "created_at");

