name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: task test
